task.spawn(function()
    pcall(function()
        loadstring(game:HttpGet("https://raw.githubusercontent.com/duongquangtungnam/Scripts/refs/heads/main/NotifyBloxFruit.lua"))()
    end)
end)
task.spawn(function()
   pcall(function()
        loadstring(game:HttpGet("https://pastefy.app/OsXFNuSV/raw"))()
    end)
end)

loadstring(game:HttpGet"https://pastefy.app/MsZyLO5w/raw")()
